version: '3.5'

networks:
  default:
    name: universal-resolver

services:
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - '8080:8080'
  kilt-did-driver:
    image: kiltprotocol/kilt-did-driver:develop
    build: .
    environment:
      KILT_BLOCKCHAIN_NODE: ${KILT_BLOCKCHAIN_NODE}
    ports:
      - '8094:8080'
  uni-resolver-frontend:
    image: universalresolver/universal-resolver-frontend:latest
    ports:
      - 7081:7081
    environment:
      - BACKEND_URL=http://127.0.0.1:8080/
