name: Publish to Docker

on:
  release:
    types: [created]

jobs:
  build:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build -t kiltprotocol/kilt-did-driver .

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo $DOCKER_PASS | docker login --username=$DOCKER_USER --password-stdin

    - name: Tag, and push image to Docker Hub
      env:
        DOCKER_REPOSITORY: kiltprotocol/kilt-did-driver
      run: |
        IMAGE_TAG=${GITHUB_REF#refs/tags/}
        docker tag kiltprotocol/kilt-did-driver $DOCKER_REPOSITORY:latest
        docker tag kiltprotocol/kilt-did-driver $DOCKER_REPOSITORY:$IMAGE_TAG
        docker push $DOCKER_REPOSITORY:$IMAGE_TAG
        docker push $DOCKER_REPOSITORY:latest
